# learning
num_classes: 2
lr: 0.005
epochs: 250
dropout: 0.1
weight_decay: 0.0001
early_stopping_patience: 30
device: 'auto'
seed: 42

# architecture
layers: 2
hidden_units: 256
use_batch_norm: true

# model-specific

# GAT
gat_heads: 4
gat_dropout: 0.1

# GATv2
gatv2_heads: 4
gatv2_dropout: 0.1

# Chebyshev
cheb_k: [2, 3]

# splits
val_size: 0.1
test_size: 0.2

# attack
p_evasion_threshold: 0.5
max_sybils: 5
max_transformations: 10
max_budget_prop: 0.4
gas_penalty_coef: 0.1
value_penalty_coef: 0.01
num_optim_steps: 100
maxiter: 100
vol_tol: 1e-10
len_tol: 1e-6